"""Verbatim and templated assets for an emitted harbor entry.

Everything here is a pure function of its arguments -- no clock, no host paths,
no environment lookups -- because these strings land in files that `diff -r`
compares between two generation runs.

`HARBOR_FILTER_PY` is a byte-for-byte copy of
`harbor-tasks/dataset/*/tests/harbor_filter.py`. It is vendored rather than
copied off disk at emit time so a generated entry stays valid if it is moved
away from this checkout.

What is NOT here any more: the Dockerfile, test.sh and solve.sh strings. They
were python-shaped, and a second language cannot be served by editing a python
template. They now live in `langs/python.py` alongside go's, behind the
`LangPlugin` contract -- and `render_dockerfile`/`render_solve_sh` are concrete
on the base class, because what they must NOT contain (the intact tree, the
oracle, the receipt) is a security invariant rather than a language detail.
"""

from __future__ import annotations

HARBOR_FILTER_PY = '''"""Pytest plugin selecting the graded allowlist while preserving collection order.

Passing 1102 node ids on the command line makes pytest execute them in the order
given, which is NOT the repo's natural collection order. This suite has
order-dependent state (hence the repo's own `xdist_group` isolation markers), and
reordering it produces failures that have nothing to do with the carved code.

Deselecting instead keeps every surviving test in its original relative position,
which is the order the coverage allowlist was measured under.

Also writes the selected count so the verifier can reject a vacuous or partial
run rather than reward it.
"""

from __future__ import annotations

import os
import pathlib

ALLOWLIST = pathlib.Path(os.environ.get('HARBOR_ALLOWLIST', '/opt/harbor/allowlist.txt'))
COUNT_OUT = pathlib.Path(os.environ.get('HARBOR_SELECTED_OUT', '/logs/verifier/selected_count.txt'))


def pytest_collection_modifyitems(config, items):
    wanted = {
        line.rstrip('\\n')
        for line in ALLOWLIST.read_text(encoding='utf-8').splitlines()
        if line.strip()
    }

    selected = []
    deselected = []
    for item in items:
        (selected if item.nodeid in wanted else deselected).append(item)

    if deselected:
        config.hook.pytest_deselected(items=deselected)
    items[:] = selected

    try:
        COUNT_OUT.parent.mkdir(parents=True, exist_ok=True)
        COUNT_OUT.write_text(f'{len(selected)}\\n', encoding='utf-8')
    except OSError:
        pass

    reporter = config.pluginmanager.get_plugin('terminalreporter')
    if reporter is not None:
        reporter.write_line(
            f'[harbor] allowlist={len(wanted)} selected={len(selected)} '
            f'deselected={len(deselected)}'
        )
'''


TASK_TOML = '''# Harbor task -- {slug}
#
# Generated by triton/harness/src/taskgen (deterministic; no LLM, no network).
# All {n_conditions} context conditions of this target share ONE prebuilt image and ONE
# oracle: the carve, the toolchain and the vendored deps are condition-
# independent. instruction.md's "Pre-loaded context" block and
# [metadata].condition are the only things that differ between them.

schema_version = "1.4"

[task]
name = "mrgctx/{slug}"
version = "1.0.0"
description = "Regenerate the carved-out {carve_scope} {func} of {upstream} under the {condition} context-provisioning condition."
authors = []
keywords = ["code-generation", "{carve_scope}-level", "context-provisioning", "{language}"]

[metadata]
id = "{entry_id}"
name = "{slug}"
repo = "{upstream}"
license = "{license}"
language = "{language}"
condition = "{condition}"
context_budget_tokens = {budget}
tokenizer = "{tokenizer}"
seed = {seed}
target_file = "{target_file}"
target_func = "{target_func}"
carve_scope = "{carve_scope}"
carved_files = {carved_files}
graded_tests = {graded_tests}
tags = ["code-generation", "{carve_scope}-level", "{language}", "{condition}"]

[verifier]
network_mode = "allowlist"
allowed_hosts = ["172.17.0.1"]
timeout_sec = 1800

[agent]
network_mode = "allowlist"
allowed_hosts = ["172.17.0.1"]
timeout_sec = 14400

[environment]
network_mode = "public"
docker_image = "{docker_image}"
build_timeout_sec = 3600
cpus = 4
memory_mb = 8192
storage_mb = 16384
gpus = 0
'''


DOCKERIGNORE = '''# Scoped ignore file for this Dockerfile (BuildKit reads <dockerfile>.dockerignore).
# The main build context is this environment/ directory; the repo checkout and
# the rest of the entry arrive as named contexts (--build-context), so only the
# stubbed carve/ tree needs to be shipped from here.
Dockerfile
Dockerfile.dockerignore
**/__pycache__/
**/*.pyc
**/.pytest_cache/
**/.ruff_cache/
'''


def render_task_toml(**kw) -> str:
    return TASK_TOML.format(**kw)
